# Default values for mongodbui
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
mongodbui_deployment:
  # Only one replica allowed
  replicaCount: 1
  image:
    imageName: master.cfc:8500/mongodb/mongodbui
    imageTag: latest
    pullPolicy: Always

mongodbui_service:
  serviceType: NodePort
