# Default values for IBM MQ
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
mq_deployment:
  # Only one replica allowed
  replicaCount: 1
  image:
    imageName: master.cfc:8500/mq/mq
    #imageName: ibmcom/mq
    imageTag: latest
    pullPolicy: Always
  serviceAccount:  mq-service-account
  #Has to be in quotes ("")
  additional_mqports:
    - "1415"
    - "1416"
    - "1417"

mq_service:
  serviceType: NodePort
  #Has to be in quotes ("")
  nodePortMap:
      1414: "32000"
      1415: "32001"
      9443: "32002"

## Persistent Volume Storage configuration.
##

mq_persistence:
  ## Enable dynamic or static (dynamic = false)  persistence using Persistent Volume Claims.
  ##
  ## Static not yet specifiablee
  dynamic: true

  ## Persistent Volume Storage Class Version.
  ##
  classVersion: beta
  ## Persistent Volume Storage Class.
  ##
  class: fast

  ## Persistent Volume Access Mode.
  ##
  accessMode: ReadWriteMany

  ## Persistent Volume Storage Size.
  ##
  size: 1Gi
