apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.ucds_service.serviceType }}
  type: {{ .Values.ucds_service.serviceType }}
  {{- end }}
  ports:
    - name: port-8443
      port: 8443
      targetPort: 8443
    - name: port-7918
      port: 7918
      targetPort: 7918
    - name: port-8080
      port: 8080
      targetPort: 8080
  selector:
    name: {{ template "fullname" . }}
