# Default values for ucds
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ucds_deployment:
  # Only one replica allowed
  replicaCount: 1
  image:
    #imageName: ibmcom/ucds
    imageName: master.cfc:8500/ucds/ucds
    imageTag: latest
    pullPolicy: IfNotPresent

ucds_service:
  serviceType: NodePort
