apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.wast_service.serviceType }}
  type: {{ .Values.wast_service.serviceType }}
  {{- end }}
  ports:
    - name: port-9043
      port: 9043
      targetPort: 9043
    - name: port-9060
      port: 9060
      targetPort: 9060
    - name: port-9080
      port: 9080
      targetPort: 9080
    - name: port-9443
      port: 9443
      targetPort: 9443
  selector:
    name: {{ template "fullname" . }}
