apiVersion: v1
name: ucda
description: ucda is a kubernetes deployment of the Urban Code Deploy Agent image
version: 0.1.1
appVersion: 9.0.1.0
home: https://hub.docker.com/r/ibmcom/ucda/
sources:
- https://hub.docker.com/r/ibmcom/ucda/
maintainers:
- name: xxyy
  email: xxyy@xxyy.com
