apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.mongodbui_service.serviceType }}
  type: {{ .Values.mongodbui_service.serviceType }}
  {{- end }}
  ports:
    - name: port-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    name: {{ template "fullname" . }}
