apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fullname" . }}-pv-claim 
  annotations:
     "volume.beta.kubernetes.io/storage-class": {{ .Values.storage.class | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
